### PR TITLE
Add MPL-2.0 license

### LINKED ISSUE #4: Add open source software license
This Mozilla repository has been identified as lacking a license. Consistent with Mozilla's [Licensing Policy](https://www.mozilla.org/en-US/MPL/license-policy/) an open source license should be applied to the code in this repository.

Please add an appropriate LICENSE.md file to the root directory of the project. In general, Mozilla's licensing policies are as follows:

-   Client-side products created by Mozilla employees or contributors should use the Mozilla Public License, Version 2.0 (MPL). 

-   Server-side products or utilities that support Mozilla products may use either the MPL or the Apache License 2.0 (Apache 2.0). 

In special cases, another license might be appropriate. If the repository is a fork of another repository it must apply the license of the original. Similarly, another license might be appropriate to match that of a broader project (for example Rust crates that Firefox depends on are published under an Apache 2.0 / MIT dual license, as that is the dual license used by the Rust programming language and projects).

Please ensure that any license added to the LICENSE.md file matches other licensing information in the repository (for example, it should match any license indicated in a setup.py or package.json file).

Mozilla staff can access more information in our Software Licensing Runbook – search for “Licensing Runbook” in Confluence to find it.

If you have any questions you can contact Daniel Nazer who can be reached at dnazer on Mozilla email or Slack.

OPENLIC-2023-01

### PR DESCRIPTION
**Pull request by rillian**
Add copyright headers and Mozilla Public License 2.0 file.

Resolves https://github.com/mozilla/rust-tooltool/issues/4

### CODE REVIEW

**Comment by rillian** [comment]
r? @danielnazer, @glandium. Please also merge, I don't have write access.

The issue asks for `LICENSE.md` but I couldn't find a markdown copy on mozilla.org, so here's a plain text version.

**Review by danielnazer — APPROVED** [review]

**Comment by rillian** [comment]
Review ping @glandium

**Comment by glandium** [comment]
I don't have write access to this repo.

**Comment by danielnazer** [comment]
I also don't have write access

**Comment by danielnazer** [comment]
@jesup do you have write access?

**Comment by rillian** [comment]
Thanks, @jesup!

**Pull request merged**
